# logo: assets/img/adri.jpg
title: Adrika Chowdhury
description:  B. Sc. in Computer Science<br>  Asian University for Women (AUW)<br>  NLP and UX/UI Enthusiast
theme: jekyll-theme-cayman
url: "https://adrikachowdhury.github.io" # Replace with your actual URL
github_username: adrikachowdhury # Replace with your GitHub username
email: adrikaprachi@gmail.com # Add your professional email
